import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { TaskProvider } from "@/context/TaskContext";
import LayoutContent from "@/components/layout/LayoutContent";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col lg:flex-row bg-zinc-50 dark:bg-zinc-950`}
      >
        <TaskProvider>
          <LayoutContent>
            {children}
          </LayoutContent>
        </TaskProvider>
      </body>
    </html>
  );
}
